"use client";

import { jsPDF } from "jspdf";
import { finalReportDisclaimer, safetyDisclaimer } from "./report-templates";
import type { AiResult, Patient, Profile, Report, Scan } from "./types";
import type { PublicReportResult } from "./report-access";

export function downloadReportPdf(args: {
  patient: Patient;
  scan: Scan;
  aiResult: AiResult;
  report: Report;
  approver?: Profile;
}) {
  const { patient, scan, aiResult, report, approver } = args;
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const margin = 48;
  let y = 52;

  doc.setFillColor(16, 119, 131);
  doc.rect(0, 0, 595, 82, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("AI-Assisted OCT Report", margin, y);
  doc.setFontSize(9);
  doc.text("Clinical OCT Reporting Service", margin, y + 18);

  if (report.status !== "approved") {
    doc.setTextColor(220, 38, 38);
    doc.setFontSize(24);
    doc.text("DRAFT - NOT APPROVED", 168, 185, { angle: -18 });
  }

  y = 116;
  doc.setTextColor(23, 32, 51);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("Patient Information", margin, y);
  doc.setFont("helvetica", "normal");
  doc.text(`Patient ID: ${patient.patientCode}`, margin, y + 20);
  doc.text(`Name: ${patient.fullName}`, margin, y + 38);
  doc.text(`Age/Gender: ${patient.age} / ${patient.gender}`, margin, y + 56);
  doc.text(`Scan Type: ${scan.scanType} | Eye: ${scan.eyeSide}`, 320, y + 20);
  doc.text(`Scan Date: ${new Date(scan.createdAt).toLocaleString()}`, 320, y + 38);

  y += 92;
  doc.setFont("helvetica", "bold");
  doc.text("AI Analysis", margin, y);
  doc.setFont("helvetica", "normal");
  doc.text(`${safetyDisclaimer}`, margin, y + 18);
  doc.text(`Prediction: ${aiResult.predictedClass}`, margin, y + 40);
  doc.text(`Confidence: ${Math.round(aiResult.confidence * 100)}%`, margin + 160, y + 40);
  doc.text(`Model: ${aiResult.modelName} ${aiResult.modelVersion}`, margin + 320, y + 40);

  y += 76;
  const sections = [
    ["Findings", report.findings],
    ["Impression", report.impression],
    ["Recommendation", report.recommendation],
    ["Doctor Notes", report.doctorNotes || "No additional notes."],
    ["Final Diagnosis", report.finalDiagnosis]
  ];

  sections.forEach(([title, body]) => {
    doc.setFont("helvetica", "bold");
    doc.text(title, margin, y);
    doc.setFont("helvetica", "normal");
    const wrapped = doc.splitTextToSize(body, 500);
    doc.text(wrapped, margin, y + 18);
    y += 32 + wrapped.length * 12;
  });

  doc.setFont("helvetica", "bold");
  doc.text("Review", margin, y + 4);
  doc.setFont("helvetica", "normal");
  doc.text(`Status: ${report.status}`, margin, y + 22);
  doc.text(`Approved by: ${approver?.fullName ?? "Not approved"}`, margin, y + 40);
  doc.text(`Approved at: ${report.approvedAt ? new Date(report.approvedAt).toLocaleString() : "Not approved"}`, margin, y + 58);

  doc.setFontSize(8);
  doc.setTextColor(71, 85, 105);
  doc.text(finalReportDisclaimer, margin, 780, { maxWidth: 500 });
  doc.text("Generated by OCT AI Report Assistant", margin, 812);

  const safeDate = new Date().toISOString().slice(0, 10);
  doc.save(`OCT_Report_${patient.patientCode}_${safeDate}.pdf`);
}

export function downloadPublicReportPdf(report: NonNullable<PublicReportResult["report"]>) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const margin = 48;
  let y = 52;

  doc.setFillColor(16, 119, 131);
  doc.rect(0, 0, 595, 82, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("AI-Assisted OCT Report", margin, y);
  doc.setFontSize(9);
  doc.text("Approved patient copy", margin, y + 18);

  y = 116;
  doc.setTextColor(23, 32, 51);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("Patient Information", margin, y);
  doc.setFont("helvetica", "normal");
  doc.text(`Patient ID: ${report.patientCode}`, margin, y + 20);
  doc.text(`Name: ${report.patientName}`, margin, y + 38);
  doc.text(`Age/Gender: ${report.age ?? "-"} / ${report.gender ?? "-"}`, margin, y + 56);
  doc.text(`Approved at: ${report.approvedAt ? new Date(report.approvedAt).toLocaleString() : "-"}`, 320, y + 20);

  y += 92;
  doc.setFont("helvetica", "bold");
  doc.text("AI Analysis", margin, y);
  doc.setFont("helvetica", "normal");
  doc.text(`${safetyDisclaimer}`, margin, y + 18);
  doc.text(`Prediction: ${report.predictedClass ?? "-"}`, margin, y + 40);
  doc.text(`Confidence: ${Math.round((report.confidence ?? 0) * 100)}%`, margin + 160, y + 40);

  y += 76;
  const sections = [
    ["Findings", report.findings],
    ["Impression", report.impression],
    ["Recommendation", report.recommendation],
    ["Doctor Notes", report.doctorNotes || "No additional notes."],
    ["Final Diagnosis", report.finalDiagnosis]
  ];

  sections.forEach(([title, body]) => {
    doc.setFont("helvetica", "bold");
    doc.text(title, margin, y);
    doc.setFont("helvetica", "normal");
    const wrapped = doc.splitTextToSize(body, 500);
    doc.text(wrapped, margin, y + 18);
    y += 32 + wrapped.length * 12;
  });

  doc.setFontSize(8);
  doc.setTextColor(71, 85, 105);
  doc.text(finalReportDisclaimer, margin, 780, { maxWidth: 500 });
  doc.text("Generated by OCT AI Report Assistant", margin, 812);

  const safeDate = new Date().toISOString().slice(0, 10);
  doc.save(`OCT_Report_${report.patientCode}_${safeDate}.pdf`);
}
